name: YeelightControl
options:
  bundleIdPrefix: com.danielkng
  deploymentTarget:
    iOS: 15.0
    macOS: 12.0
targets:
  YeelightControl:
    type: application
    platform: iOS
    sources: [Sources/App]
    dependencies:
      - target: Core
      - target: Features
      - target: UI
  Core:
    type: framework
    platform: iOS
    sources: [Sources/Core]
  Features:
    type: framework
    platform: iOS
    sources: [Sources/Features]
    dependencies:
      - target: Core
  UI:
    type: framework
    platform: iOS
    sources: [Sources/UI]
    dependencies:
      - target: Core
      - target: Features
  Widget:
    type: app-extension
    platform: iOS
    sources: [Sources/Widget]
    dependencies:
      - target: Core
