name: YeelightControl
options:
  bundleIdPrefix: de.knng.app
  deploymentTarget:
    iOS: 15.0
  xcodeVersion: "15.2"
  generateEmptyDirectories: true
  createIntermediateGroups: true

settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1

targets:
  YeelightControl:
    type: application
    platform: iOS
    sources:
      - path: Sources/App
        name: App
      - path: Sources/Models
        name: Models
      - path: Sources/Views
        name: Views
      - path: Sources/Controllers
        name: Controllers
      - path: Sources/Utils
        name: Utils
      - path: Sources/Extensions
        name: Extensions
      - path: Sources/Services
        name: Services
    info:
      path: Sources/App/Info.plist
      properties:
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: de.knng.app.yeelightcontrol
        TARGETED_DEVICE_FAMILY: 1
        ENABLE_PREVIEWS: YES

  YeelightWidget:
    type: app-extension
    platform: iOS
    dependencies:
      - target: YeelightControl
    sources:
      - path: Sources/Widget
    info:
      path: Sources/Widget/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: de.knng.app.yeelightcontrol.widget
        TARGETED_DEVICE_FAMILY: 1
        ENABLE_PREVIEWS: YES

  YeelightControlTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: YeelightControl

schemes:
  YeelightControl:
    build:
      targets:
        YeelightControl: all
        YeelightWidget: all
    test:
      targets:
        - name: YeelightControlTests
          parallelizable: true
          randomExecutionOrder: true
