name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-14
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install XcodeGen
        run: brew install xcodegen
      
      - name: Create Build Directory Structure
        run: |
          mkdir -p Build/Sources
          cp -R Sources/* Build/Sources/
      
      - name: Setup Project
        run: ./Scripts/setup_xcode_project.sh
      
      - name: Build
        run: |
          cd Build
          xcodebuild -scheme YeelightControl -configuration Debug -destination "platform=iOS Simulator,name=iPhone 16 Pro Max" 