name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Install XcodeGen
      run: |
        brew update
        brew install xcodegen
        xcodegen --version

    - name: Set up project
      run: |
        pwd
        ls -la
        chmod +x Scripts/*.sh
        ./Scripts/setup_xcode_project.sh
        ls -la

    - name: Show available destinations
      run: xcodebuild -showdestinations -scheme YeelightControl

    - name: Build
      run: |
        set -o pipefail && xcodebuild clean build \
          -scheme YeelightControl \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=YES \
          -configuration Debug \
          | xcpretty

    - name: Run tests
      run: |
        set -o pipefail && xcodebuild test \
          -scheme YeelightControl \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=YES \
          -configuration Debug \
          | xcpretty
