name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'

    - name: Install XcodeGen
      run: brew install xcodegen

    - name: Set up project
      run: |
        chmod +x Scripts/*.sh
        ./Scripts/setup_xcode_project.sh

    - name: Build
      run: |
        xcodebuild clean build \
          -scheme YeelightControl \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Run tests
      run: |
        xcodebuild test \
          -scheme YeelightControl \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
