name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Install XcodeGen
      run: |
        brew update
        brew install xcodegen
        xcodegen --version

    - name: Set up project
      run: |
        echo "Current directory:"
        pwd
        echo "\nInitial directory contents:"
        ls -la
        echo "\nMaking scripts executable:"
        chmod +x Scripts/*.sh
        echo "\nRunning setup script:"
        ./Scripts/setup_xcode_project.sh
        echo "\nVerifying generated files:"
        ls -la Build/
        ls -la Resources/Configs/
        echo "\nChecking project.yml content:"
        cat Resources/Configs/project.yml
        echo "\nChecking Info.plist files:"
        cat Resources/Configs/App-Info.plist
        cat Resources/Configs/Widget-Info.plist

    - name: Show available destinations
      run: xcodebuild -showdestinations -scheme YeelightControl -project Build/YeelightControl.xcodeproj

    - name: Build
      run: |
        set -o pipefail && xcodebuild clean build \
          -scheme YeelightControl \
          -project Build/YeelightControl.xcodeproj \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=YES \
          -configuration Debug \
          | xcpretty

    - name: Run tests
      run: |
        set -o pipefail && xcodebuild test \
          -scheme YeelightControl \
          -project Build/YeelightControl.xcodeproj \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=YES \
          -configuration Debug \
          | xcpretty
